"""doc metadata and process

Revision ID: 656e01e93251
Revises: bfdeadcc63c5
Create Date: 2026-04-26 19:25:22.337335

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '656e01e93251'
down_revision = 'bfdeadcc63c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
