"""add document metadata and process

Revision ID: b40cde070d11
Revises: 001
Create Date: 2026-04-26 10:16:54.869230

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b40cde070d11'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('meta_key', sa.String(length=255), nullable=False),
    sa.Column('meta_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_metadata_document_id'), 'document_metadata', ['document_id'], unique=False)
    op.create_table('document_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('process_status', sa.String(length=255), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_process_document_id'), 'document_process', ['document_id'], unique=False)
    op.drop_index(op.f('idx_messages_created_at'), table_name='chat_messages')
    op.drop_index(op.f('idx_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('idx_messages_sources'), table_name='chat_messages', postgresql_using='gin')
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.drop_constraint(op.f('fk_messages_session'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.drop_index(op.f('idx_sessions_updated_at'), table_name='chat_sessions')
    op.drop_index(op.f('idx_sessions_user_id'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_sessions_user'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('idx_chunks_document_index'), table_name='document_chunks')
    op.drop_index(op.f('idx_chunks_embedding_hnsw'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.drop_constraint(op.f('fk_chunks_document'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'])
    op.drop_index(op.f('idx_documents_status'), table_name='documents')
    op.drop_index(op.f('idx_documents_uploaded_at'), table_name='documents')
    op.drop_index(op.f('idx_documents_uploaded_by'), table_name='documents')
    op.drop_constraint(op.f('fk_documents_user'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'])
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_user'), 'documents', 'users', ['uploaded_by'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_index(op.f('idx_documents_uploaded_at'), 'documents', [sa.literal_column('uploaded_at DESC')], unique=False)
    op.create_index(op.f('idx_documents_status'), 'documents', ['status'], unique=False)
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_chunks_document'), 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.create_index(op.f('idx_chunks_embedding_hnsw'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_chunks_document_index'), 'document_chunks', ['document_id', 'chunk_index'], unique=True)
    op.create_index(op.f('idx_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sessions_user'), 'chat_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.create_index(op.f('idx_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_sessions_updated_at'), 'chat_sessions', [sa.literal_column('updated_at DESC')], unique=False)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_messages_session'), 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.create_index(op.f('idx_messages_sources'), 'chat_messages', ['sources'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('idx_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.drop_index(op.f('ix_document_process_document_id'), table_name='document_process')
    op.drop_table('document_process')
    op.drop_index(op.f('ix_document_metadata_document_id'), table_name='document_metadata')
    op.drop_table('document_metadata')
    # ### end Alembic commands ###
