"""restore missing indexes and fix naming

Revision ID: bfdeadcc63c5
Revises: b40cde070d11
Create Date: 2026-04-26 10:17:36.874793

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'bfdeadcc63c5'
down_revision = 'b40cde070d11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chat_messages_sources', 'chat_messages', ['sources'], unique=False, postgresql_using='gin')
    op.create_index('ix_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_chat_messages_sources', table_name='chat_messages', postgresql_using='gin')
    # ### end Alembic commands ###
